name: animated_layout
description: "A wrap widget where layout changes animate, that also helps with insertion and deletion."
version: 0.9.0
homepage: https://github.com/makoConstruct/animated_layout
license: MIT

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  circular_reveal_animation: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
