name: animated_containers
description: "Flex and Wrap widgets with animated insertion, deletion, and layout changes."
version: 1.2.0
homepage: https://github.com/makoConstruct/animated_containers
license: MIT

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  # this needs to be updated to at least 2.0.2, waiting on https://github.com/qwert2603/circular_reveal_animation/pull/10 . If it hasn't been publishe3d by july, fork it.
  # circular_reveal_animation: ^2.0.2
  circular_reveal_animation: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
