name: animated_containers
description: "A wrap widget that animates insertion, removal, and layout changes."
version: 0.9.0
homepage: https://github.com/makoConstruct/animated_flex
license: MIT

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  circular_reveal_animation: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
